name: 'Setup Conan'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - run: pip3 install -r requirements.txt
      shell: bash

    - if: ${{ runner.os == 'Windows' }}
      run: echo "CONAN_HOME=${{ runner.temp }}\\.c2" >> $GITHUB_ENV
      shell: bash

    - run: conan profile detect --force
      shell: bash

    - run: conan remote remove "*"
      shell: bash

    - name: Create Conan hook to reduce conandata
      shell: bash
      run: |
        HOOK_DIR="$(conan config home)/extensions/hooks"
        HOOK_FILE="$HOOK_DIR/hook_reduce_conandata.py"

        mkdir -p "$HOOK_DIR"
        echo "from conan.tools.files import trim_conandata" > "$HOOK_FILE"
        echo "def post_export(conanfile):" >> "$HOOK_FILE"
        echo "  if conanfile.conan_data:" >> "$HOOK_FILE"
        echo "    trim_conandata(conanfile)" >> "$HOOK_FILE"

    - if: ${{ runner.os == 'Windows' }}
      name: Remove system OpenSSL directory
      shell: bash
      run: |
        paths=(
          "/c/Program Files/OpenSSL"
          "/c/Program Files/OpenSSL-Win64"
          "/c/Program Files (x86)/OpenSSL"
        )
        
        for path in "${paths[@]}"; do
          if [ -d "$path" ]; then
            echo "Removing $path"
            rm -rf "$path"
          else
            echo "Not found: $path"
          fi
        done