name: 'Setup Conan'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - run: pip3 install -r requirements.txt
      shell: bash

    - if: ${{ runner.os == 'Windows' }}
      run: echo "CONAN_HOME=${{ runner.temp }}\\.c2" >> $GITHUB_ENV
      shell: bash

    - run: conan profile detect --force
      shell: bash

    - run: conan remote remove "*"
      shell: bash
