# This is a basic workflow to help you get started with Actions

name: FreeBSD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - '**' 
  workflow_dispatch: {}


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: freebsd
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: 'pip' # caching pip dependencies
      - run: python3 -m pip install -r requirements.txt
      - name: Generate Job Matrix
        id: set-matrix
        run: |
          python3 main.py          
          MATRIX=$(cat matrix.yml)
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
  
  FreeBSD:
    needs: generate-matrix
    if: ${{ fromJSON( needs.generate-matrix.outputs.matrix ).include[0] }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      
    runs-on: macos-12

    env:
      CONAN_MAKE_PROGRAM: "gmake"
      CC: clang
      CXX: clang++
      CONAN_SYSREQUIRES_MODE: enabled
      MAKE: gmake
    steps:
    - name: Checkout CCI
      uses: actions/checkout@v3
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.ref }}
        path: CCI
    - name: run
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        envs: 'CONAN_MAKE_PROGRAM CC CXX CONAN_SYSREQUIRES_MODE MAKE'
        usesh: true
        prepare: pkg install -y cmake py39-pip py39-sqlite3 python3 sudo pkgconf gmake bash perl5 p5-XML-Parser git && ln -s /usr/local/bin/perl /usr/bin/perl
        run: |
          pip install conan
          conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
          conan config set hooks.conan-center
          conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/${{ matrix.version }}@ -b missing -o b2:toolset=clang
 
