# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - '**' 
  workflow_dispatch: {}


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: freebsd
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "pip3 install pyyaml requests aiohttp packaging"
      - name: Generate Job Matrix
        id: set-matrix
        run: |
          python3 main.py          
          MATRIX=$(cat matrix.yml)
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
  
  FreeBSD:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      
    runs-on: macos-latest

    env:
      CONAN_MAKE_PROGRAM: "gmake"
      CC: clang
      CXX: clang++
      CONAN_SYSREQUIRES_MODE: enabled
    steps:
    - name: Checkout CCI
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.ref }}
        path: CCI
    - name: run
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        envs: 'CONAN_MAKE_PROGRAM CC CXX CONAN_SYSREQUIRES_MODE'
        usesh: true
        prepare: pkg install -y cmake conan python3 sudo pkgconf gmake
        run: conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/${{ matrix.version }}@ -b missing
 