on:
  issue_comment:
    types: [created]

jobs:
  comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const regexpCoordinates = /\[All logs\]\((?<url>.*)\)/g;
            for (const match of context.payload.comment.body.matchAll(regexpCoordinates))
            {
              console.log(match.groups.url);
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
